#!/bin/bash

# Use manifest-tool to create the manifest, given the experimental
# "docker manifest" command isn't available yet on Docker Hub

echo "${DOCKER_TAG} + ${SOURCE_BRANCH}" 

curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.2/manifest-tool-linux-amd64
chmod +x manifest-tool

#./manifest-tool push from-spec multi-arch-manifest.yaml
./manifest-tool push from-args --platforms linux/amd64,linux/arm/v7 --template wagoautomation/pfc-firmware-base-image:${DOCKER_TAG} --target wagoautomation/pfc-firmware-base-image:${DOCKER_TAG}